import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const menu = [{ label: 'My orders', icon: 'receipt-long' as const }, { label: 'Saved products', icon: 'favorite-border' as const }, { label: 'Delivery addresses', icon: 'location-on' as const }, { label: 'Help center', icon: 'help-outline' as const }];

export default function AccountScreen() {
  return <SafeAreaView style={styles.safe}><View style={styles.content}><Text style={styles.kicker}>PERSONAL SPACE</Text><Text style={styles.title}>Your account</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>A</Text></View><View><Text style={styles.name}>Alex Morgan</Text><Text style={styles.email}>alex.morgan@email.com</Text></View><MaterialIcons name="edit" size={20} color="#E76F51" /></View><Text style={styles.section}>QUICK ACCESS</Text>{menu.map((item) => <View style={styles.menuItem} key={item.label}><View style={styles.menuIcon}><MaterialIcons name={item.icon} size={21} color="#E76F51" /></View><Text style={styles.menuText}>{item.label}</Text><MaterialIcons name="chevron-right" size={22} color="#A5AFBB" /></View>)}<View style={styles.member}><MaterialIcons name="verified" size={25} color="#F2B134" /><View><Text style={styles.memberTitle}>Home+ member</Text><Text style={styles.memberText}>Enjoy early access and member prices.</Text></View></View></View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F8FAFC' }, content: { padding: 20 }, kicker: { color: '#E76F51', fontSize: 11, fontWeight: '800', letterSpacing: 1.3 }, title: { color: '#152238', fontSize: 30, fontWeight: '800', marginTop: 5, marginBottom: 22 }, profile: { flexDirection: 'row', alignItems: 'center', gap: 13, backgroundColor: '#FFF', padding: 17, borderRadius: 16, marginBottom: 28 }, avatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: '#152238', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#A8DADC', fontSize: 21, fontWeight: '800' }, name: { color: '#152238', fontSize: 16, fontWeight: '800' }, email: { color: '#8490A0', fontSize: 12, marginTop: 4 }, section: { color: '#8A96A5', fontSize: 11, fontWeight: '800', letterSpacing: 1.2, marginBottom: 10 }, menuItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', padding: 14, borderBottomWidth: 1, borderBottomColor: '#F0F2F5' }, menuIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#FFF1EC', alignItems: 'center', justifyContent: 'center', marginRight: 13 }, menuText: { color: '#152238', fontSize: 14, fontWeight: '700', flex: 1 }, member: { flexDirection: 'row', gap: 12, backgroundColor: '#FFF8E5', padding: 16, borderRadius: 16, marginTop: 25 }, memberTitle: { color: '#8B6712', fontWeight: '800', fontSize: 13 }, memberText: { color: '#A68D4A', fontSize: 12, marginTop: 4 } });