import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { Link } from 'expo-router';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const items = [
  { name: 'Nồi chiên không dầu Pro 5L', price: '2.290.000đ', quantity: '1', icon: 'outdoor-grill' as const, color: '#FFE8D5' },
  { name: 'Máy lọc không khí thông minh', price: '3.290.000đ', quantity: '1', icon: 'air' as const, color: '#DFF3F4' },
];

export default function CartScreen() {
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>GIỎ HÀNG CỦA BẠN</Text><Text style={styles.title}>Giỏ hàng</Text><View style={styles.delivery}><MaterialIcons name="local-shipping" size={22} color="#1A8A72" /><View><Text style={styles.deliveryTitle}>Miễn phí giao hàng</Text><Text style={styles.deliveryText}>Nhận hàng trong 2-4 ngày làm việc</Text></View></View>{items.map((item) => <View style={styles.item} key={item.name}><View style={[styles.itemImage, { backgroundColor: item.color }]}><MaterialIcons name={item.icon} size={42} color="#152238" /></View><View style={styles.itemInfo}><Text style={styles.itemName}>{item.name}</Text><Text style={styles.itemMeta}>Số lượng: {item.quantity}</Text><Text style={styles.itemPrice}>{item.price}</Text></View><MaterialIcons name="delete-outline" size={22} color="#9AA5B4" /></View>)}<View style={styles.summary}><View style={styles.line}><Text style={styles.label}>Tạm tính</Text><Text style={styles.value}>5.580.000đ</Text></View><View style={styles.line}><Text style={styles.label}>Phí giao hàng</Text><Text style={styles.free}>MIỄN PHÍ</Text></View><View style={[styles.line, styles.totalLine]}><Text style={styles.total}>Tổng cộng</Text><Text style={styles.total}>5.580.000đ</Text></View><Link href="/modal" style={styles.checkout}><Text style={styles.checkoutText}>Tiến hành thanh toán</Text><MaterialIcons name="arrow-forward" size={19} color="#FFF" /></Link></View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F6F8FB' }, content: { padding: 20, paddingBottom: 32 }, kicker: { color: '#E76F51', fontSize: 11, fontWeight: '800', letterSpacing: 1.3 }, title: { color: '#152238', fontSize: 30, fontWeight: '800', marginTop: 5, marginBottom: 22 }, delivery: { flexDirection: 'row', gap: 12, alignItems: 'center', padding: 15, backgroundColor: '#EAF8F0', borderRadius: 14, marginBottom: 15 }, deliveryTitle: { color: '#1A6B5C', fontWeight: '800', fontSize: 13 }, deliveryText: { color: '#579487', fontSize: 12, marginTop: 3 }, item: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', borderRadius: 14, padding: 12, marginBottom: 10, shadowColor: '#152238', shadowOpacity: 0.04, shadowRadius: 8, elevation: 1 }, itemImage: { width: 78, height: 78, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, itemInfo: { flex: 1, marginLeft: 13 }, itemName: { color: '#152238', fontSize: 14, fontWeight: '800' }, itemMeta: { color: '#8A96A5', fontSize: 12, marginTop: 6 }, itemPrice: { color: '#E76F51', fontSize: 15, fontWeight: '800', marginTop: 7 }, summary: { backgroundColor: '#FFF', borderRadius: 14, padding: 18, marginTop: 12, shadowColor: '#152238', shadowOpacity: 0.04, shadowRadius: 8, elevation: 1 }, line: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 13 }, label: { color: '#8490A0', fontSize: 13 }, value: { color: '#152238', fontSize: 13, fontWeight: '700' }, free: { color: '#1A8A72', fontSize: 13, fontWeight: '800' }, totalLine: { borderTopWidth: 1, borderTopColor: '#EDF0F3', paddingTop: 15, marginTop: 2, marginBottom: 17 }, total: { color: '#152238', fontSize: 18, fontWeight: '800' }, checkout: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 9, backgroundColor: '#152238', padding: 15, borderRadius: 10 }, checkoutText: { color: '#FFF', fontWeight: '800', fontSize: 14 } });