import ResourcePage from '../components/ResourcePage';
import { resourceApi } from '../api/resource';
import { money, dateTime } from '../utils/format';
type Voucher = { ma_voucher: number; code: string; loai: string; gia_tri: number; don_toi_thieu: number; giam_toi_da: number | null; bat_dau: string; ket_thuc: string; gioi_han: number; moi_khach: number; hoat_dong: boolean; da_dung: number };
const base=resourceApi<Voucher>('/voucher');
const payload=(v:Partial<Voucher>)=>({...v, bat_dau: new Date(v.bat_dau!).toISOString(), ket_thuc: new Date(v.ket_thuc!).toISOString(), gia_tri:Number(v.gia_tri),don_toi_thieu:Number(v.don_toi_thieu),gioi_han:Number(v.gioi_han),moi_khach:Number(v.moi_khach),giam_toi_da:v.giam_toi_da==null?null:Number(v.giam_toi_da), hoat_dong:!!v.hoat_dong});
const api={get:base.get,list:()=>base.list(),create:(v:Partial<Voucher>)=>base.create(payload(v)),update:(id:number,v:Partial<Voucher>)=>base.update(id,payload(v))};
const local=(value:string)=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,19);};
export default function VouchersPage(){return <ResourcePage<Voucher> title="Mã giảm giá" idKey="ma_voucher" api={api} searchKeys={['code']} defaults={{loai:'PhanTram',gia_tri:10,don_toi_thieu:1000000,giam_toi_da:200000,gioi_han:100,moi_khach:1,hoat_dong:true}}
 extra={<p>Mỗi đơn dùng một mã. Hủy đơn sẽ hoàn lượt. Mã đã có lịch sử sử dụng chỉ được bật/tắt; tạo mã mới để đổi điều kiện.</p>}
 prepare={v=>({...v,bat_dau:local(v.bat_dau),ket_thuc:local(v.ket_thuc),hoat_dong:!!v.hoat_dong})}
 columns={[{title:'Mã',dataIndex:'code'},{title:'Giảm',render:(_,v)=>v.loai==='PhanTram'?`${v.gia_tri}%`:money(v.gia_tri)},{title:'Đơn tối thiểu',dataIndex:'don_toi_thieu',render:money},{title:'Giảm tối đa',dataIndex:'giam_toi_da',render:v=>v?money(v):'—'},{title:'Hết hạn',dataIndex:'ket_thuc',render:dateTime},{title:'Lượt',render:(_,v)=>`${v.da_dung}/${v.gioi_han}`},{title:'Hoạt động',dataIndex:'hoat_dong',render:v=>v?'Bật':'Tắt'}]}
 fields={[{name:'code',label:'Mã giảm giá',required:true,rules:[{pattern:/^[A-Za-z0-9_-]{3,32}$/,message:'Mã gồm 3–32 chữ, số, dấu gạch'}]},{name:'loai',label:'Loại giảm',kind:'select',required:true,options:[{value:'PhanTram',label:'Phần trăm'},{value:'SoTien',label:'Số tiền'}]},{name:'gia_tri',label:'Giá trị giảm (% hoặc đồng)',kind:'number',required:true},{name:'don_toi_thieu',label:'Đơn tối thiểu (đồng)',kind:'number',required:true},{name:'giam_toi_da',label:'Giảm tối đa (bắt buộc với phần trăm)',kind:'number'},{name:'bat_dau',label:'Bắt đầu',kind:'datetime',required:true},{name:'ket_thuc',label:'Hết hạn',kind:'datetime',required:true},{name:'gioi_han',label:'Tổng số lượt',kind:'number',required:true},{name:'moi_khach',label:'Lượt tối đa mỗi khách',kind:'number',required:true},{name:'hoat_dong',label:'Hoạt động',kind:'switch'}]} />;}
